version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: turkestate_postgres
    environment:
      POSTGRES_USER: turkestate_admin
      POSTGRES_PASSWORD: admin_password_super_secure
      POSTGRES_DB: turkestate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U turkestate_admin -d turkestate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: turkestate_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7-alpine
    container_name: turkestate_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  es_data:
